language: python

before_install:
  - git clone https://github.com/STIXProject/schemas-test.git tests

install:
  - sudo apt-get update
  - sudo apt-get install libxml2-dev libxslt-dev zlib1g-dev
  - pip install -q stix-validator

# checks against the latest commit to master of schema (may be ahead of official release)
# manifest = a list of testfiles to run, i.e. `ls -1 $test_dir [...] >> manifest.cfg`
script: python test_runner.py --test-case-repository tests test_manifest.cfg

branches:
  only:
    - master

notifications:
  email:
    - stix-commits-list@lists.mitre.org
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/1fbfa85a0bb8108ad060
    on_success: change  
    on_failure: always  
    on_start: false     

